/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.asr.gui;


//import com.example.asr.gui.components.ToggleSwitch;
import com.example.asr.transcriber.MicTranscriber;
import com.example.asr.vosk.VoskService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.swing.*;
import javax.sound.sampled.LineUnavailableException;
import java.awt.*;
import java.io.IOException;
import java.util.concurrent.atomic.AtomicReference;

/**
 *
 * @author by-nreyes
 */

public class LiveSessionPanel extends javax.swing.JPanel {

    /**
     * Creates new form LiveSessionPanel
     */
    public LiveSessionPanel(MainFrame mainFrame) {
                initComponents();
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton = new javax.swing.JToggleButton();
        jScrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(246, 244, 210));

        jToggleButton.setBackground(new java.awt.Color(241, 156, 121));
        jToggleButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jToggleButton.setForeground(new java.awt.Color(70, 63, 58));
        jToggleButton.setSelected(false);
        jToggleButton.setText("OFF");
        jToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButtonMouseClicked(evt);
            }
        });
        jToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(10);
        textArea.setEditable(false);
        jScrollPane.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jToggleButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void jToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButtonMouseClicked
        // TODO add your handling code here:
        
        if (jToggleButton.isSelected()){
            jToggleButton.setOpaque(true);
            jToggleButton.setText("ON");
            jToggleButton.setBackground(new Color(212,224,155));
            startTranscripcion();    
            
        } else {
            stopTranscripcion();
        }
        
       
    }//GEN-LAST:event_jToggleButtonMouseClicked

    private void jToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonActionPerformed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_jToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

    // Worker y transcriptor activos
    private transient com.example.asr.transcriber.MicTranscriber transcriber;
    private transient javax.swing.SwingWorker<Void, String> worker;

    private void startTranscripcion() {
        // Evitar múltiples workers
        if (worker != null && !worker.isDone()) return;

        try {
            transcriber = new MicTranscriber(MainFrame.getVoskService());
        } catch (Exception e) {
            textArea.append("No se pudo inicializar el servicio Vosk: " + e.getMessage() + "\n");
            return;
        }

        // recomendado para no bloquear la interfaz
        worker = new SwingWorker<Void, String>() {

            @Override
            protected Void doInBackground() throws Exception {
                try {
                    transcriber.startTranscription(text -> {
                        if (text != null && !text.isEmpty()) {
                            publish(text); // Enviar a UI thread
                        }
                    });
                } catch (LineUnavailableException | IOException e) {
                    publish("ERROR: " + e.getMessage());
                } catch (Exception e) {
                    publish("ERROR inesperado: " + e.getMessage());
                }

                return null;
            }

            @Override
            protected void process(java.util.List<String> chunks) {
                for (String text : chunks) {
                    textArea.append(">>> " + text + "\n");
                }
            }

        };

        worker.execute();
        textArea.append("[Transcripción iniciada]\n");

    }

    private void stopTranscripcion() {
        // detener el transcriptor y cancelar worker
        try {
            if (transcriber != null) {
                transcriber.stop();
            }
        } catch (Exception e) {
            textArea.append("Error al detener transcripción: " + e.getMessage() + "\n");
        }

        if (worker != null && !worker.isDone()) {
            worker.cancel(true);
        }

        jToggleButton.setText("OFF");
        jToggleButton.setBackground(new Color(241,156,121));
        textArea.append("[Transcripción detenida]\n");
    }
}
